import Head from 'next/head'
import {FplMiniLeagueAPIResponse} from "@/utils/types";
import {useEffect, useState} from "react";
import axios from "axios";
export default function Home() {
    async function fetchFplMiniLeagueApiData(): Promise<FplMiniLeagueAPIResponse> {
        try {
            const response = await axios.get<FplMiniLeagueAPIResponse>('https://43vewwe578.execute-api.eu-west-1.amazonaws.com/default/fpl-mini-league-api');
            return response.data;
        } catch (error) {
            console.error(error);
            throw error;
        }
    }

    const [apiData, setApiData] = useState<FplMiniLeagueAPIResponse | null>(null);

    useEffect(() => {
        async function fetchData() {
            const data = await fetchFplMiniLeagueApiData();
            setApiData(data);
        }

        fetchData();
    }, []);

    if (!apiData) {
        return <div>Loading...</div>;
    }
    else {
        console.log(apiData)
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
