import Head from 'next/head'
import {FplMiniLeagueAPIResponse} from "@/utils/types";
import {useEffect, useState} from "react";
import axios from "axios";
import CurrentLeagueTable from "@/components/CurrentLeagueTable";
import LeagueHistory from "@/components/LeagueHistory";
import DetailedHistoryTable from "@/components/DetailedLeagueHistory";
import LeaderBoard from "@/components/LeaderBoard";
import CurrentWinner from "@/components/CurrentWinner";
import Header from "@/components/Header";

export default function Home() {
    async function fetchFplMiniLeagueApiData(): Promise<FplMiniLeagueAPIResponse> {
        try {
            const response = await axios.get<FplMiniLeagueAPIResponse>('https://43vewwe578.execute-api.eu-west-1.amazonaws.com/default/fpl-mini-league-api');
            return response.data;
        } catch (error) {
            console.error(error);
            throw error;
        }
    }

    const [apiData, setApiData] = useState<FplMiniLeagueAPIResponse | null>(null);

    useEffect(() => {
        async function fetchData() {
            const data = await fetchFplMiniLeagueApiData();
            setApiData(data);
        }

        fetchData();
    }, []);

    if (!apiData) {
        return <div>Loading...</div>;
    }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header/>
        <div className="container">
        <h1>The David Goggins Invitational</h1>
        <div>
            <CurrentLeagueTable current_league_standings={apiData.league_standings}/>
            <br/>
            <LeagueHistory league_history={apiData.league_history}/>
            <br/>
            <DetailedHistoryTable league_history={apiData.league_history}/>
            <br/>
            <LeaderBoard data={apiData}/>
            <br/>
            <CurrentWinner league_history={apiData.league_history}/>
        </div>
            <br/>
        </div>
    </>
  )
}
